Repository teragrep/cfe_18, pull requests merged in 2025-04, with the labels that each got.

#117 system versioned tables feature requires testuser to have access to m…
  .github/workflows/ci.yaml
Labels: bug

#119 Allow release yaml to use mysql trans_action registry aswell.
  .github/workflows/release.yaml
Labels: bug

#130 Add copyright comment to all documentation files
  src/docs/examples/capture/captureGroup.adoc
  src/docs/examples/capture/captureMeta.adoc
  src/docs/examples/capture/fileCaptureDefinition.adoc
  src/docs/examples/capture/relpCaptureDefinition.adoc
  src/docs/examples/capture/storage.adoc
  src/docs/examples/capture/storageCapture.adoc
  src/docs/examples/capture/storageFlow.adoc
  src/docs/examples/capture/tag.adoc
  src/docs/examples/flow.adoc
  src/docs/examples/host/hostFile.adoc
  src/docs/examples/host/hostGroup.adoc
  src/docs/examples/host/hostMeta.adoc
  src/docs/examples/host/hostMetaIP.adoc
  src/docs/examples/host/hostMetaInterface.adoc
  src/docs/examples/host/hostRelp.adoc
  src/docs/examples/hub.adoc
  src/docs/examples/linkage.adoc
  src/docs/examples/main.adoc
  src/docs/examples/sink.adoc
Labels: documentation, review

#131 Rename main.adoc's title to "Example API calls for integration"
  src/docs/examples/main.adoc
Labels: documentation, review

#128 Specify that captureMeta is only for file-based captures
  src/docs/examples/capture/captureMeta.adoc
  src/docs/examples/main.adoc
Labels: documentation, review

#133 Add request method to all example documentations
  src/docs/examples/capture/captureGroup.adoc
  src/docs/examples/capture/captureMeta.adoc
  src/docs/examples/capture/fileCaptureDefinition.adoc
  src/docs/examples/capture/relpCaptureDefinition.adoc
  src/docs/examples/capture/storage.adoc
  src/docs/examples/capture/storageCapture.adoc
  src/docs/examples/capture/storageFlow.adoc
  src/docs/examples/flow.adoc
  src/docs/examples/host/hostFile.adoc
  src/docs/examples/host/hostGroup.adoc
  src/docs/examples/host/hostMeta.adoc
  src/docs/examples/host/hostMetaIP.adoc
  src/docs/examples/host/hostMetaInterface.adoc
  src/docs/examples/host/hostRelp.adoc
  src/docs/examples/host/hub.adoc
  src/docs/examples/linkage.adoc
  src/docs/examples/sink.adoc
Labels: documentation, review

#138 jwt token generation script and small instructions
  quadlet/jwt_generate.sh
Labels: enhancement

#71 Refactor returning error
  src/main/java/com/teragrep/cfe18/handlers/CaptureController.java
  src/main/java/com/teragrep/cfe18/handlers/CaptureGroupController.java
  src/main/java/com/teragrep/cfe18/handlers/FileProcessingTypeController.java
  src/main/java/com/teragrep/cfe18/handlers/FlowController.java
  src/main/java/com/teragrep/cfe18/handlers/HostGroupController.java
  src/main/java/com/teragrep/cfe18/handlers/LinkageController.java
  src/main/java/com/teragrep/cfe18/handlers/StorageController.java
Labels: enhancement

#112 Cfe04transforms
  src/main/java/com/teragrep/cfe18/Cfe04TransformMapper.java
  src/main/java/com/teragrep/cfe18/handlers/Cfe04TransformController.java
  src/main/java/com/teragrep/cfe18/handlers/entities/Cfe04Transform.java
  src/main/resources/com/teragrep/cfe18/Cfe04TransformMapper.xml
  src/main/resources/db/migration/R__Procedure_Remove_cfe_04_transform.sql
  src/main/resources/db/migration/R__Procedure_Retrieve_All_cfe_04_transform.sql
  src/main/resources/db/migration/R__Procedure_Retrieve_transforms_for_cfe_04.sql
  src/main/resources/db/migration/R__Procedure_add_cfe_04_transform.sql
  src/main/resources/db/migration/V19__add_transform_cfe_04.sql
  src/main/resources/mybatis-config.xml
  src/test/java/com/teragrep/cfe18/controllerTests/Cfe04TransformControllerTest.java
Labels: enhancement
